### ISSUE TITLE
Grid: 1.9.13 throws this.element.setAttribute is not a function on grid creation

### ISSUE THREAD

**Issue by kaliif** [atatanasov/gijgo#579]
Was using gijgo 1.9.10 until now but tried to upgrade to latest today. The old version was working fine but with new, on page load "not a function error" is thrown: Stack trace:

```
jquery.js:3819 jQuery.Deferred exception: this.element.setAttribute is not a function TypeError: this.element.setAttribute is not a function
    at GijgoGrid.gj.widget.initJS (http://127.0.0.1:7800/js/gijgo.js:188:18)
    at GijgoGrid.init (http://127.0.0.1:7800/js/gijgo.js:14728:36)
    at new GijgoGrid (http://127.0.0.1:7800/js/gijgo.js:5791:22)
    at jQuery.fn.init.$.fn.grid (http://127.0.0.1:7800/js/gijgo.js:5810:28)
    at HTMLDocument.<anonymous> (http://127.0.0.1:8000/static/case/js/sample_booking_table.js:235:37)
    at mightThrow (http://127.0.0.1:8000/static/admin/js/vendor/jquery/jquery.js:3535:29)
    at process (http://127.0.0.1:8000/static/admin/js/vendor/jquery/jquery.js:3603:12) undefined
jQuery.Deferred.exceptionHook @ jquery.js:3819
process @ jquery.js:3607
setTimeout (async)
(anonymous) @ jquery.js:3641
fire @ jquery.js:3269
fireWith @ jquery.js:3399
fire @ jquery.js:3407
fire @ jquery.js:3269
fireWith @ jquery.js:3399
ready @ jquery.js:3879
completed @ jquery.js:3889

```

jQuery version 3.3.1 from django, the line from my script (sample_booking_table.js) in stack trace simply calls $('#myid').grid(... config...);

**Comment by kwsim539** [comment]
I'm having the same issue. I'm using jQuery 3.4.1. Stack trace:
`scripts.js:formatted:1484 jQuery.Deferred exception: this.element.setAttribute is not a function TypeError: this.element.setAttribute is not a function
    at GijgoGrid.gj.widget.initJS (http://localhost:3000/js/scripts.js:31:3419)
    at GijgoGrid.init (http://localhost:3000/js/scripts.js:31:140688)
    at new GijgoGrid (http://localhost:3000/js/scripts.js:31:51278)
    at k.fn.init.a.fn.grid (http://localhost:3000/js/scripts.js:31:51740)
    at HTMLDocument.<anonymous> (http://localhost:3000/leak-investigation.html:261:43)
    at e (http://localhost:3000/js/scripts.js:7:29453)
    at t (http://localhost:3000/js/scripts.js:7:29755) undefined
k.Deferred.exceptionHook @ scripts.js:formatted:7
t @ scripts.js:formatted:7
setTimeout (async)
(anonymous) @ scripts.js:formatted:7
c @ scripts.js:formatted:7
fireWith @ scripts.js:formatted:7
fire @ scripts.js:formatted:7
c @ scripts.js:formatted:7
fireWith @ scripts.js:formatted:7
ready @ scripts.js:formatted:7
B @ scripts.js:formatted:7
`
